### ISSUE TITLE
Can't get kerberos ticket

### ISSUE THREAD

**Issue by andrewm659** [larrabee/freeipa-password-reset#2]
I was able to get this installed and mostly working.  I had to upgrade pip.  Something you might want to put in the documentation.  

However when I go to test this, I get an error about kerberos ticket not being able to be accessed.

If I check the /var/log/messages I see this:
`Failed to initialize credentials using keytab [MEMORY:/etc/krb5.keytab]: Preauthentication failed. Unable to create GSSAPI-encrypted LDAP connection.`

**Comment by larrabee** [comment]
Hello. 
Thanks for feedback ;)
Few questions: 
1. Do u change "KEYTAB_PATH" option in settings.py? 
2. Do u run it from "ldap-passwd-reset" user?
3. Can u provide output of `systemctl status ldap-passwd-reset -l` with error message?
4. Can u check keytab retrieving with command `sudo -u ldap-passwd-reset -i kinit ldap-passwd-reset -t /opt/data/IPAPasswordReset/ldap-passwd-reset.keytab -k`. 

Of course you should change username or install path if u change it.

**Comment by andrewm659** [comment]
So I think my problem might that I didn't run it as the ldap_passwd_reset user.  Let me redo the setup.

**Comment by andrewm659** [comment]
So I built a test server and installed the password reset on there.  Built the python virtual env as the ldap-passwd-reset user.  Now I can't view the web page.  I have nothing in the apache logs nor in messages showing why.

**Comment by larrabee** [comment]
Hmm, you can try replace `ExecStart` option in systemd unit with `ExecStart=/opt/data/IPAPasswordReset/virtualenv/bin/python /opt/data/IPAPasswordReset/PasswordReset/manage.py runserver 0.0.0.0:8000`, exec `systemctl daemon-reload` and restart service with `systemctl restart ldap-passwd-reset`.
After this actions you can connect to service directly (without apache) on `http://<YOUR_IP>:8000` and debug what happening.

**Comment by andrewm659** [comment]
So that didn't help either.  Going to try doing the python virtual env as root.

**Comment by andrewm659** [comment]
I see this in the access logs.
`
10.1.6.248 - - [30/Mar/2018:11:54:55 -0500] "GET /reset HTTP/1.1" 404 203
10.1.6.248 - - [30/Mar/2018:11:54:55 -0500] "GET /favicon.ico HTTP/1.1" 404 209
`

**Comment by larrabee** [comment]
You should use`http://<YOUR_IP>:8000/reset/`, not `http://<YOUR_IP>:8000/reset`, last slash are important.

**Comment by andrewm659** [comment]
Oh man!  Thank you so much!

**Comment by larrabee** [comment]
It's working? ;)

**Comment by andrewm659** [comment]
Now in the web ui for the password reset I get no module named jinja...is this another pyhon module?

**Comment by andrewm659** [comment]
So I installed the python jinja2 module.  Now i'm getting a
`global name 'botocore' is not defined`

**Comment by larrabee** [comment]
`botocore` should have been installed with `boto3` package. Do you install requirements with  `pip install -r requirements.txt`?

**Comment by andrewm659** [comment]
I did. Yes.

**Comment by larrabee** [comment]
Can you show output of `./virtualenv/bin/pip freeze`?

**Comment by andrewm659** [comment]
`pip freeze
appdirs==1.4.3
asn1crypto==0.24.0
boto3==1.4.4
botocore==1.5.71
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
cryptography==2.2.2
decorator==4.0.11
Django==1.11
django-freeipa-auth==0.1.dev4
dnspython==1.15.0
docutils==0.13.1
enum34==1.1.6
freeipa==4.6.3
futures==3.1.1
gssapi==1.4.1
httplib2==0.10.3
idna==2.5
ipa==4.6.3
ipaclient==4.6.3
ipaddress==1.0.18
ipalib==4.6.3
ipaplatform==4.6.3
ipapy==0.0.8.0
ipapython==4.6.3
Jinja2==2.10
jmespath==0.9.3
MarkupSafe==1.0
netaddr==0.7.19
netifaces==0.10.6
packaging==16.8
pyasn1==0.2.3
pyasn1-modules==0.0.8
pycparser==2.17
pyOpenSSL==17.5.0
pyparsing==2.2.0
python-dateutil==2.6.0
python-ldap==3.0.0
pytz==2017.2
qrcode==6.0
redis==2.10.5
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.10
six==1.10.0
uritemplate==3.0.0
urllib3==1.22`

**Comment by andrewm659** [comment]
Now I get this 
`'API' object has no attribute 'Backend'`

**Comment by larrabee** [comment]
Do u use FreeIPA 4.6? It looking like they change API of ipalib. Need time to research this.

**Comment by andrewm659** [comment]
I am running FreeIPA 4.5.0-22.  4.6 is in Fedora repo.

I'm on CentOS 7.4

**Comment by larrabee** [comment]
But you have installed `ipaclient==4.6.3` and `ipa==4.6.3 ` python packages. Its strange.

**Comment by andrewm659** [comment]
can you specify the version of ipaclient in pip?  I can try to remove that and install an older version.

**Comment by larrabee** [comment]
I found the problem, its my bad. I use Backend plugin, that require server context and only need to be installed on the IPA server. I will try to find another way, that not require Backend method.

**Comment by andrewm659** [comment]
I am installing this on the IPA server.

**Comment by andrewm659** [comment]
So I was able to uninstall all the 4.6.3 pip libraries.  I then tried install anything related to 4.5.0.

Here is the output
` pip install ipalib==4.5.0 ipa==4.5.0 ipaplatform==4.5.0 freeipa==4.5.0 ipaclient==4.5.0
Collecting ipalib==4.5.0
  Using cached ipalib-4.5.0-py2.py3-none-any.whl
Collecting ipa==4.5.0
  Downloading ipa-4.5.0-py2.py3-none-any.whl
Collecting ipaplatform==4.5.0
  Downloading ipaplatform-4.5.0-py2.py3-none-any.whl
Collecting freeipa==4.5.0
  Downloading freeipa-4.5.0-py2.py3-none-any.whl
Requirement already satisfied: ipaclient==4.5.0 in ./virtualenv/lib/python2.7/site-packages
Collecting python-nss>=0.16 (from ipalib==4.5.0)
  Using cached python-nss-1.0.1.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-XcsUmw/python-nss/setup.py", line 409, in <module>
        sys.exit(main(sys.argv))
      File "/tmp/pip-build-XcsUmw/python-nss/setup.py", line 333, in main
        nss_include_dir  = find_include_dir(['nss3', 'nss'],   ['nss.h',  'pk11pub.h'], include_roots=include_roots)
      File "/tmp/pip-build-XcsUmw/python-nss/setup.py", line 94, in find_include_dir
        raise ValueError("unable to locate include directory containing header files %s" % include_files)
    ValueError: unable to locate include directory containing header files ['nss.h', 'pk11pub.h']

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-XcsUmw/python-nss/`

**Comment by larrabee** [comment]
Try run it from ldap-passwd-reset user:
1. `klist -A` - You should see something like
```
Ticket cache: KEYRING:persistent:100:100
Default principal: ldap-passwd-reset@TEST.COM

Valid starting       Expires              Service principal
03/30/2018 17:51:25  03/30/2018 20:46:20  HTTP/ldap.test.com@TEST.COM
03/29/2018 20:46:20  03/30/2018 20:46:20  krbtgt/TEST.COM@TEST.COM
```
2. `ipa user-show admin` - You should see info about admin user.

**Comment by larrabee** [comment]
I think install this libraries from pip is bad idea. Use versions, provided by system repo. You can reinstall its with `yum reinstall python2-ipaclient python2-ipalib`

**Comment by andrewm659** [comment]
So what do I do about the systemd service?

**Comment by larrabee** [comment]
What's with systemd service? 
If your test machine not contain any private data you can provide ssh access for me and i can help with debug faster.

**Comment by andrewm659** [comment]
I don't at the moment.  So right now since you are having me not use the pip install.  How would I activate the password reset portal?

**Comment by larrabee** [comment]
No, i say what you should not use pip to install system packages like ipalib==4.5.0 or ipa==4.5.0, because they part of FreeIPA install and they installed by yum.  

Do u try `klist -A` from previous message?

**Comment by andrewm659** [comment]
So I did what you said and installed all of the packages in the CentOS 7 and EPEL repo listed in the requirements.txt file.  However now I'm getting a http 500 error.  I have not done a klist -A

**Comment by andrewm659** [comment]
So the issue w/ the HTTP 500 error was from a different server.  I ran through the setup again and it worked but still got a error about botocore not being globally defined.  So I put import botocore into the manage.py and restarted the service.  It now works without complaint. 

However right now its complaining that I have too many password reset attempts.

More updates to come!

**Comment by larrabee** [comment]
Do u have installed and running redis? By default app connect to redis to 127.0.0.1:6379, but u can change it in settings.py

**Comment by andrewm659** [comment]
Yes.  Redis is installed.  I'm getting to the web page.

**Comment by andrewm659** [comment]
Here is what in the /var/log/http/error_log


`[Mon Apr 02 08:49:16.960946 2018] [:warn] [pid 29827] [client 10.1.6.140:37286] failed to set perms (3140) on file (/var/run/ipa/ccaches/ldap-passwd-reset@corp.stage)!, referer: https://freeipa01-dev.corp.stage/ipa/xml
[Mon Apr 02 08:49:16.979809 2018] [:error] [pid 29426] ipa: INFO: [jsonserver_session] ldap-passwd-reset@corp.stage: ping(): SUCCESS
[Mon Apr 02 08:49:16.988589 2018] [:warn] [pid 29827] [client 10.1.6.140:37286] failed to set perms (3140) on file (/var/run/ipa/ccaches/ldap-passwd-reset@corp.stage)!, referer: https://freeipa01-dev.corp.stage/ipa/xml
[Mon Apr 02 08:49:17.019370 2018] [:error] [pid 29425] ipa: INFO: [jsonserver_session] ldap-passwd-reset@corp.stage: user_show/1(u'andrew.meyer', version=u'2.228'): SUCCESS`

**Comment by andrewm659** [comment]
I'm almost there.

**Comment by larrabee** [comment]
Are you got `Too much retries. Try later.` error? It's brute force protection. You can increase limits in settings (`LIMIT_MAX_SEND` and `LIMIT_MAX_VALIDATE_RETRY`) or flush redis cache with redis-cli and `FLUSHDB` command.

**Comment by larrabee** [comment]
Time limit configured too with `LIMIT_TIME` option and by default is 24h.

**Comment by andrewm659** [comment]
Getting this still:
`Apr  2 09:48:02 freeipa01-dev python: ipa: ERROR: Could not create log_dir u'/home/ldap-passwd-reset/.ipa/log'
Apr  2 09:48:02 freeipa01-dev python: ipa: INFO: trying https://freeipa01-dev.corp.stage/ipa/session/json
Apr  2 09:48:02 freeipa01-dev python: ipa: INFO: [try 1]: Forwarding 'schema' to json server 'https://freeipa01-dev.corp.stage/ipa/session/json'
Apr  2 09:48:03 freeipa01-dev python: ipa: WARNING: Failed to write schema: [Errno 13] Permission denied: '/home/ldap-passwd-reset'
Apr  2 09:48:03 freeipa01-dev python: ipa: WARNING: Failed to write server info: [Errno 13] Permission denied: '/home/ldap-passwd-reset'
Apr  2 09:48:05 freeipa01-dev python: ipa: INFO: trying https://freeipa01-dev.corp.stage/ipa/session/json
Apr  2 09:48:05 freeipa01-dev python: ipa: INFO: [try 1]: Forwarding 'user_show/1' to json server 'https://freeipa01-dev.corp.stage/ipa/session/json'
Apr  2 09:48:06 freeipa01-dev python: [02/Apr/2018 14:48:06] "POST /reset/gettoken/ HTTP/1.1" 200 5661


[Mon Apr 02 09:48:02.223578 2018] [:warn] [pid 30532] [client 10.1.6.140:37984] failed to set perms (3140) on file (/var/run/ipa/ccaches/ldap-passwd-reset@corp.stage)!, referer: https://freeipa01-dev.corp.stage/ipa/xml
[Mon Apr 02 09:48:02.263243 2018] [:error] [pid 30458] ipa: INFO: [jsonserver_session] ldap-passwd-reset@corp.stage: ping(): SUCCESS
[Mon Apr 02 09:48:02.270739 2018] [:warn] [pid 30532] [client 10.1.6.140:37984] failed to set perms (3140) on file (/var/run/ipa/ccaches/ldap-passwd-reset@corp.stage)!, referer: https://freeipa01-dev.corp.stage/ipa/xml
[Mon Apr 02 09:48:02.792261 2018] [:error] [pid 30457] ipa: INFO: [jsonserver_session] ldap-passwd-reset@corp.stage: schema(version=u'2.170'): SUCCESS
[Mon Apr 02 09:48:05.754424 2018] [:warn] [pid 30531] [client 10.1.6.140:37990] failed to set perms (3140) on file (/var/run/ipa/ccaches/ldap-passwd-reset@corp.stage)!, referer: https://freeipa01-dev.corp.stage/ipa/xml
[Mon Apr 02 09:48:05.771647 2018] [:error] [pid 30458] ipa: INFO: [jsonserver_session] ldap-passwd-reset@corp.stage: ping(): SUCCESS
[Mon Apr 02 09:48:05.779257 2018] [:warn] [pid 30531] [client 10.1.6.140:37990] failed to set perms (3140) on file (/var/run/ipa/ccaches/ldap-passwd-reset@corp.stage)!, referer: https://freeipa01-dev.corp.stage/ipa/xml
[Mon Apr 02 09:48:06.166267 2018] [:error] [pid 30457] ipa: INFO: [jsonserver_session] ldap-passwd-reset@corp.stage: user_show/1(u'andrew.meyer', version=u'2.228'): SUCCESS`

**Comment by larrabee** [comment]
I think you have wrong permissions or owner on `/home/ldap-passwd-reset'` dir.

**Comment by andrewm659** [comment]
`[root@freeipa01-dev ~]# ls -la /home/|grep -i ldap
drwx------   4 ldap-passwd-reset ldap-passwd-reset  112 Apr  2 10:09 ldap-passwd-reset
[root@freeipa01-dev ~]#`

**Comment by larrabee** [comment]
SELinux? try to set permissible mod for it

**Comment by andrewm659** [comment]
SELinux is disabled.
[root@freeipa01-dev ~]# getenforce
Disabled
[root@freeipa01-dev ~]#

**Comment by andrewm659** [comment]
So is the firewall.

**Comment by andrewm659** [comment]
Could this be a problem? 
[root@freeipa01-dev ~]# ls -la /var/run/ipa/ccaches/ldap-passwd-reset@corp.stage
-rw------- 1 ipaapi ipaapi 4430 Apr  2 08:21 /var/run/ipa/ccaches/ldap-passwd-reset@corp.stage
[root@freeipa01-dev ~]#

**Comment by larrabee** [comment]
On my server this file have same owner and permissions. Its ok.

**Comment by andrewm659** [comment]
Found this - https://pagure.io/freeipa/issue/7032

**Comment by larrabee** [comment]
No activity, closed

**Comment by LinuxPersonEC** [comment]
On `freeipa-server-4.9.3-4.fc34.x86_64` I'm seeing:
```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server
```
and in the Apache error log:

```
[Tue Jun 08 10:51:54.805720 2021] [:warn] [pid 105957:tid 106013] [client x.x.x.x:36258] failed to set perms (3140) on file (/run/ipa/ccaches/ldap-passwd-reset@OURSERVER.EDU-4G7APH)!, referer: https://OURSERVER.EDU/ipa/xml
[Tue Jun 08 10:51:54.807047 2021] [wsgi:error] [pid 105093:tid 105505] [remote x.x.x.x:36258] ipa: DEBUG: WSGI wsgi_dispatch.__call__:
[Tue Jun 08 10:51:54.807189 2021] [wsgi:error] [pid 105093:tid 105505] [remote x.x.x.x:36258] ipa: DEBUG: WSGI jsonserver_session.__call__:
[Tue Jun 08 10:51:55.043334 2021] [wsgi:error] [pid 105093:tid 105505] [remote x.x.x.x:36258] ipa: DEBUG: Created connection context.ldap2_139888456625600
[Tue Jun 08 10:51:55.043470 2021] [wsgi:error] [pid 105093:tid 105505] [remote x.x.x.x:36258] ipa: DEBUG: WSGI jsonserver.__call__:
[Tue Jun 08 10:51:55.043639 2021] [wsgi:error] [pid 105093:tid 105505] [remote x.x.x.x:36258] ipa: DEBUG: WSGI WSGIExecutioner.__call__:
[Tue Jun 08 10:51:55.052948 2021] [wsgi:error] [pid 105093:tid 105505] [remote x.x.x.x:36258] ipa: DEBUG: raw: user_show('ouruser', all=True, version='2.240')
[Tue Jun 08 10:51:55.053219 2021] [wsgi:error] [pid 105093:tid 105505] [remote x.x.x.x:36258] ipa: DEBUG: user_show('ouruser', rights=False, all=True, raw=False, version='2.240', no_members=False)
[Tue Jun 08 10:51:55.056829 2021] [wsgi:error] [pid 105093:tid 105505] [remote x.x.x.x:36258] ipa: DEBUG: retrieving schema for SchemaCache url=ldapi://%2Frun%2Fslapd-OURSERVER-EDU.socket conn=<ldap.ldapobject.SimpleLDAPObject object at 0x7f3a5129fbb0>
[Tue Jun 08 10:51:55.460259 2021] [wsgi:error] [pid 105093:tid 105505] [remote x.x.x.x:36258] ipa: INFO: [jsonserver_session] ldap-passwd-reset@OURSERVER.EDU: user_show/1('ouruser', all=True, version='2.240'): SUCCESS
[Tue Jun 08 10:51:55.460415 2021] [wsgi:error] [pid 105093:tid 105505] [remote x.x.x.x:36258] ipa: DEBUG: [jsonserver_session] ldap-passwd-reset@OURSERVER.EDU: user_show/1('ouruser', all=True, version='2.240'): SUCCESS etime=416407566
[Tue Jun 08 10:51:55.461892 2021] [wsgi:error] [pid 105093:tid 105505] [remote x.x.x.x:36258] ipa: DEBUG: Destroyed connection context.ldap2_139888456625600
```
