### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by ados8** [larrabee/freeipa-password-reset#62]
I sunk a few hours of troubleshooting before posting but have not been able to resolve.
I'm using freeIPA with Fedora.
Followed the steps and went over multiple times but when going to ipa.domain.com/reset its service unavailable
![image](https://user-images.githubusercontent.com/49982433/174965670-ceac290f-8c9f-44d3-b25f-2bbade4deaa8.png)

Logging into freeIPA is no issue and rebooting the server in mid access drops the page so content is trying to load but failing.
Any solutions?

**Comment by Andriilasiuk** [comment]
Same problem, any solution?

**Comment by tceydeliler** [comment]
I ahve same problem after modify provider section
`[root@ipa1 IPAPasswordReset]# systemctl status ldap-passwd-reset.service
● ldap-passwd-reset.service - FreeIPA Password Reset Service
     Loaded: loaded (/etc/systemd/system/ldap-passwd-reset.service; enabled; preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2024-05-20 08:40:35 +03; 18s ago
    Process: 2294 ExecStart=/opt/data/IPAPasswordReset/virtualenv/bin/python /opt/data/IPAPasswordReset/PasswordReset/manage.py runserver (code=exited, status=1/FAILURE)
   Main PID: 2294 (code=exited, status=1/FAILURE)
        CPU: 187ms

May 20 08:40:35 ipa1.yasar.local systemd[1]: ldap-passwd-reset.service: Main process exited, code=exited, status=1/FAILURE
May 20 08:40:35 ipa1.yasar.local systemd[1]: ldap-passwd-reset.service: Failed with result 'exit-code'.
`

**Comment by tceydeliler** [comment]
run service status command:
```
[root@ipa1 migrations]# systemctl status ldap-passwd-reset.service
● ldap-passwd-reset.service - FreeIPA Password Reset Service
     Loaded: loaded (/etc/systemd/system/ldap-passwd-reset.service; enabled; preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2024-05-20 09:02:31 +03; 5s ago
    Process: 2618 ExecStart=/opt/data/IPAPasswordReset/virtualenv/bin/python /opt/data/IPAPasswordReset/PasswordReset/manage.py runserver (code=exited, status=1/FAILURE)
   Main PID: 2618 (code=exited, status=1/**FAILURE**)
        CPU: 177ms

May 20 09:02:31 ipa1.yasar.local systemd[1]: ldap-passwd-reset.service: Main process exited, code=exited, status=1/FAILURE
May 20 09:02:31 ipa1.yasar.local systemd[1]: ldap-passwd-reset.service: Failed with result 'exit-code'.
```
Then run service manually 
/opt/data/IPAPasswordReset/virtualenv/bin/python /opt/data/IPAPasswordReset/PasswordReset/manage.py

Here is my result:
```
[root@ipa1 yum.repos.d]# /opt/data/IPAPasswordReset/virtualenv/bin/python /opt/data/IPAPasswordReset/PasswordReset/manage.py runserver
[root@ipa1 yum.repos.d]# /opt/data/IPAPasswordReset/virtualenv/bin/python /opt/data/IPAPasswordReset/PasswordReset/manage.py runserver
Traceback (most recent call last):
  File "/opt/data/IPAPasswordReset/PasswordReset/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/data/IPAPasswordReset/virtualenv/lib/python3.9/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/data/IPAPasswordReset/virtualenv/lib/python3.9/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/opt/data/IPAPasswordReset/virtualenv/lib/python3.9/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/opt/data/IPAPasswordReset/virtualenv/lib/python3.9/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/data/IPAPasswordReset/virtualenv/lib/python3.9/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/data/IPAPasswordReset/PasswordReset/PasswordReset/settings.py", line 166, in <module>
    "smtp_from": FreeIPA, #With None its copy value from smtp_user
**NameError: name 'FreeIPA' is not defined**

```
Output shown what is wrong.
I find and fix may error like this
